set(CMAKE_CROSSCOMPILING FALSE)

set(CMAKE_ASM_COMPILER ${GCMAKE_ASM_COMPILER})
set(CMAKE_C_COMPILER ${GCMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER ${GCMAKE_CXX_COMPILER})

set(CMAKE_C_STANDARD ${GCMAKE_C_STANDARD})
set(CMAKE_C_STANDARD_REQUIRED ON)

set(CMAKE_CXX_STANDARD ${GCMAKE_CXX_STANDARD})
set(CMAKE_CXX_STANDARD_REQUIRED ON)

