set(CMAKE_SYSTEM_NAME ${GCMAKE_CROSSCOMPILING_SYSTEM_NAME})
set(CMAKE_SYSTEM_PROCESSOR ${GCMAKE_CROSSCOMPILING_SYSTEM_PROCESSOR})
set(CMAKE_CROSSCOMPILING TRUE)

string(REPLACE "-gcc" "" toolchain_prefix "${GCMAKE_C_COMPILER}")

set(CMAKE_AR            ${toolchain_prefix}-ar)
set(CMAKE_ASM_COMPILER  ${GCMAKE_ASM_COMPILER})
set(CMAKE_C_COMPILER    ${GCMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER  ${GCMAKE_CXX_COMPILER})
set(CMAKE_LINKER        ${toolchain_prefix}-ld         CACHE FILEPATH "linker")
set(CMAKE_NM            ${toolchain_prefix}-nm         CACHE FILEPATH "gcc-nm")
set(CMAKE_RANLIB        ${toolchain_prefix}-ranlib     CACHE FILEPATH "gcc-ranlib")
set(CMAKE_OBJCOPY       ${toolchain_prefix}-objcopy    CACHE FILEPATH "objcopy")
set(CMAKE_OBJDUMP       ${toolchain_prefix}-objdump    CACHE FILEPATH "objdump")
set(CMAKE_STRIP         ${toolchain_prefix}-strip      CACHE FILEPATH "strip")
set(CMAKE_SIZE          ${toolchain_prefix}-size       CACHE FILEPATH "size")
set(CMAKE_STRINGS       ${toolchain_prefix}-strings    CACHE FILEPATH "strings")

list(APPEND CMAKE_FIND_ROOT_PATH ${GCMAKE_CROSSCOMPILING_TOOLCHAIN_ROOT})

list(APPEND CMAKE_INSTALL_RPATH "${GCMAKE_CROSSCOMPILING_TOOLCHAIN_ROOT}/lib")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)

set(CMAKE_C_STANDARD ${GCMAKE_C_STANDARD})
set(CMAKE_C_STANDARD_REQUIRED ON)

set(CMAKE_CXX_STANDARD ${GCMAKE_CXX_STANDARD})
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_CROSSCOMPILING_EMULATOR ${GCMAKE_CROSSCOMPILING_EMULATOR} CACHE FILEPATH "Path to the emulator for the target system.")