# FILE should have been validated before this function call.
function(gcmake_get_value_file FILE KEY SEPERATOR VALUE)
    file(STRINGS ${FILE} line_list)
    foreach(line ${line_list})
        if(line MATCHES "^(${KEY})${SEPERATOR}(.*)$")
            if(NOT "${CMAKE_MATCH_2}" STREQUAL "")
                set(VALUE ${CMAKE_MATCH_2} PARENT_SCOPE)
            else()
                set(VALUE ${GCMAKE_VALUE_NOT_FOUND} PARENT_SCOPE)
            endif()
            return()
        else()
            continue()
        endif()
    endforeach()
    set(VALUE ${GCMAKE_VALUE_NOT_FOUND} PARENT_SCOPE)
endfunction()
