enable_testing()

if(${GCMAKE_GCTEST_ENABLE} STREQUAL ${GCMAKE_VALUE_NOT_FOUND})
    message(FATAL_ERROR "${GCMAKE_GCTEST_ENABLE_KEY} is not defined. Please define it.")
endif()
list(FIND GCMAKE_VALID_GCTEST_ENABLE ${GCMAKE_GCTEST_ENABLE} VALID_GCTEST_ENABLE_RESULT)
if(${VALID_GCTEST_ENABLE_RESULT} EQUAL -1)
    message(FATAL_ERROR "${GCMAKE_GCTEST_ENABLE_KEY} must be true or false.")
endif()

if(${GCMAKE_GCTEST_ENABLE} STREQUAL "true")
    if(DEV_LOCAL)
        message(STATUS "DEV_LOCAL")
        list(APPEND CMAKE_FIND_ROOT_PATH "$ENV{GCTEST_HOME}/gctest-core/build/install")
    endif()
    find_package(gctest-core CONFIG 1.1.2 REQUIRED)
endif()
