if(NOT EXISTS ${GCMAKE_PROJECT_PROPERTIES_FILE})
    message(FATAL_ERROR "Gcmake.properties file must be exist in the top level cmake project structor.")
endif()

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_CMAKE_VERSION_KEY} "=" VALUE)
set(GCMAKE_CMAKE_VERSION ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_PROJECT_NAMESPACE_KEY} "=" VALUE)
set(GCMAKE_PROJECT_NAMESPACE ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_PROJECT_NAME_KEY} "=" VALUE)
set(GCMAKE_PROJECT_NAME ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_PROJECT_VERSION_KEY} "=" VALUE)
set(GCMAKE_PROJECT_VERSION ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_PROJECT_DESCRIPTION_KEY} "=" VALUE)
set(GCMAKE_PROJECT_DESCRIPTION ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_PROJECT_CONTACT_KEY} "=" VALUE)
set(GCMAKE_PROJECT_CONTACT ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_BUILD_TYPE_KEY} "=" VALUE)
set(GCMAKE_BUILD_TYPE ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_ASM_FLAGS_KEY} "=" VALUE)
set(GCMAKE_ASM_FLAGS ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_ASM_COMPILER_KEY} "=" VALUE)
set(GCMAKE_ASM_COMPILER ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_C_COMPILER_KEY} "=" VALUE)
set(GCMAKE_C_COMPILER ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_C_STANDARD_KEY} "=" VALUE)
set(GCMAKE_C_STANDARD ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_C_FLAGS_KEY} "=" VALUE)
set(GCMAKE_C_FLAGS ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_CXX_COMPILER_KEY} "=" VALUE)
set(GCMAKE_CXX_COMPILER ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_CXX_STANDARD_KEY} "=" VALUE)
set(GCMAKE_CXX_STANDARD ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_CXX_FLAGS_KEY} "=" VALUE)
set(GCMAKE_CXX_FLAGS ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_EXE_LINKER_FLAGS_KEY} "=" VALUE)
set(GCMAKE_EXE_LINKER_FLAGS ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_CPACK_GENERATOR_KEY} "=" VALUE)
set(GCMAKE_CPACK_GENERATOR ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_CROSSCOMPILING_KEY} "=" VALUE)
set(GCMAKE_CROSSCOMPILING ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_CROSSCOMPILING_SYSTEM_NAME_KEY} "=" VALUE)
set(GCMAKE_CROSSCOMPILING_SYSTEM_NAME ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_CROSSCOMPILING_SYSTEM_PROCESSOR_KEY} "=" VALUE)
set(GCMAKE_CROSSCOMPILING_SYSTEM_PROCESSOR ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_CROSSCOMPILING_TOOLCHAIN_ROOT_KEY} "=" VALUE)
set(GCMAKE_CROSSCOMPILING_TOOLCHAIN_ROOT ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_CROSSCOMPILING_EMULATOR_KEY} "=" VALUE)
set(GCMAKE_CROSSCOMPILING_EMULATOR ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_CROSSCOMPILING_EMULATOR_PARAMETERS_KEY} "=" VALUE)
set(GCMAKE_CROSSCOMPILING_EMULATOR_PARAMETERS ${VALUE})

gcmake_get_value_file(${GCMAKE_PROJECT_PROPERTIES_FILE} ${GCMAKE_GCTEST_ENABLE_KEY} "=" VALUE)
set(GCMAKE_GCTEST_ENABLE ${VALUE})





