enable_testing()

if(${GCMAKE_GCTEST_ENABLE} STREQUAL ${GCMAKE_VALUE_NOT_FOUND})
    message(FATAL_ERROR "${GCMAKE_GCTEST_ENABLE_KEY} is not defined. Please define it.")
endif()
list(FIND GCMAKE_VALID_GCTEST_ENABLE ${GCMAKE_GCTEST_ENABLE} VALID_GCTEST_ENABLE_RESULT)
if(${VALID_GCTEST_ENABLE_RESULT} EQUAL -1)
    message(FATAL_ERROR "${GCMAKE_GCTEST_ENABLE_KEY} must be true or false.")
endif()

if(${GCMAKE_GCTEST_ENABLE} STREQUAL "true")
    if(OWN_TEST_LOCAL OR DEV_LOCAL)
        message(STATUS "OWN TEST LOCAL")
        list(APPEND CMAKE_FIND_ROOT_PATH "$ENV{GCTEST_HOME}/gctest-core/build-local/install")
    elseif(OWN_TEST_ARM32 OR DEV_ARM32)
        message(STATUS "OWN TEST ARM32")   
        list(APPEND CMAKE_FIND_ROOT_PATH "$ENV{GCTEST_HOME}/gctest-core/build-arm32/install")
    elseif(OWN_TEST_ARM64 OR DEV_ARM64)
        message(STATUS "OWN TEST ARM64")
        list(APPEND CMAKE_FIND_ROOT_PATH "$ENV{GCTEST_HOME}/gctest-core/build-arm64/install")                
    endif()
    find_package(gctest-core CONFIG 1.0.0 REQUIRED)
endif()
