set(CPACK_DEB_COMPONENT_INSTALL ON)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

get_property(package_dependencies GLOBAL PROPERTY GCMAKE_PROJECT_PACKAGE_DEPENDENCIES)
list(APPEND CPACK_DEBIAN_PACKAGE_DEPENDS "${package_dependencies}")

set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
if(${GCMAKE_CROSSCOMPILING} STREQUAL "true")
    if(${GCMAKE_CROSSCOMPILING_SYSTEM_PROCESSOR} STREQUAL "aarch64")
        set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE arm64)
    endif()
endif()
